version: '3.9'
services:
  backend:
    image: node:16
    container_name: store_manager_api
    platform: linux/x86_64
    restart: 'always'
    tty: true
    stdin_open: true
    command: bash -c "npm install && npx prisma migrate deploy && npm run dev"
    working_dir: /app
    volumes:
      - './:/app'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_NAME=StoreManager
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE